name: vaxhax
favicon: null
layout_spectrum: 0.36850994639098644
typography_spectrum: 0.5987678314559162
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.15071647590957582
  lightness: 0.11014080117456615
  saturation: 0.5925991828553379
  rhythmicContrast: 0.43385140667669475
purpose: []
